-- DEPRECATED — do not run.
-- Production DB keeps bluebook_* table names; the app uses /magiclog routes with bluebook_* tables.
-- See migration_bluebook.sql and migration_magiclog_storage_only.sql instead.
